language: php
php:
  - '7.3'

install:
  - composer install
  - pecl install ast

script:
  - composer test-coverage
  - composer lint
  - composer md
  - composer analyze-noop

after_success:
  - bash <(curl -s https://codecov.io/bash)
